site_name: wundertax/mkdocs
site_description: 'Custom MkDocs Container For Wundertax'
site_author: 'wundertax'
#repo_name: 'wundertax/documentation'
#repo_url: 'https://github.com/wundertax/documentation'
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'Blue'
    accent: 'Blue'
    #  feature:
    #tabs: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true


# Repository
repo_name: wundertax/mkdocs
repo_url: https://github.com/wundertax/mkdocs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 - wundertax'

# Page tree
pages:
  - Home: index.md
